version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - app
